"""update tables

Revision ID: 6b26e958d83a
Revises: 22677d1b2596
Create Date: 2025-05-06 23:02:06.929827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b26e958d83a'
down_revision: Union[str, None] = '22677d1b2596'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regions', sa.Column('federal_district_code', sa.String(length=10), nullable=False))
    op.drop_constraint('regions_region_code_hh_key', 'regions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('regions_region_code_hh_key', 'regions', ['region_code_hh'])
    op.drop_column('regions', 'federal_district_code')
    # ### end Alembic commands ###
