"""add location column to vacancies

Revision ID: f4aeba698cd9
Revises: 6b26e958d83a
Create Date: 2025-07-28 12:20:40.834812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4aeba698cd9'
down_revision: Union[str, None] = '6b26e958d83a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacancies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vacancy_id', sa.String(length=300), nullable=False),
    sa.Column('location', sa.String(length=300), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('salary', sa.String(length=300), nullable=False),
    sa.Column('vacancy_url', sa.Text(), nullable=False),
    sa.Column('vacancy_source', sa.String(length=100), nullable=False),
    sa.Column('employer_name', sa.String(length=300), nullable=False),
    sa.Column('employer_location', sa.String(length=300), nullable=False),
    sa.Column('employer_phone', sa.String(length=100), nullable=False),
    sa.Column('employer_code', sa.String(length=100), nullable=False),
    sa.Column('experience_required', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('employment_type', sa.String(length=200), nullable=False),
    sa.Column('schedule', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vacancy_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacancies')
    # ### end Alembic commands ###
