"""add_blocked_tokens_table

Revision ID: f95c88255e49
Revises: 09b7895b1860
Create Date: 2025-11-05 21:51:31.104378

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f95c88255e49'
down_revision: Union[str, None] = '09b7895b1860'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jti', sa.String(), nullable=False),
    sa.Column('exp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blocked_tokens_id'), 'blocked_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_blocked_tokens_jti'), 'blocked_tokens', ['jti'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blocked_tokens_jti'), table_name='blocked_tokens')
    op.drop_index(op.f('ix_blocked_tokens_id'), table_name='blocked_tokens')
    op.drop_table('blocked_tokens')
    # ### end Alembic commands ###
