"""Initial migration

Revision ID: 22677d1b2596
Revises: 
Create Date: 2025-04-29 17:22:48.022924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22677d1b2596'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_name', sa.String(length=100), nullable=False),
    sa.Column('region_code_tv', sa.String(length=10), nullable=False),
    sa.Column('region_code_hh', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_code_hh'),
    sa.UniqueConstraint('region_code_tv'),
    sa.UniqueConstraint('region_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('regions')
    # ### end Alembic commands ###
