"""change employer_location from String(300) to String(1000)

Revision ID: 3ddd6c15200c
Revises: f4aeba698cd9
Create Date: 2025-08-22 21:06:49.614598

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3ddd6c15200c'
down_revision: Union[str, None] = 'f4aeba698cd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vacancies', 'employer_location',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=1000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vacancies', 'employer_location',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)
    # ### end Alembic commands ###
