"""Initial migration with all tables

Revision ID: 906e6e76a815
Revises: 
Create Date: 2026-02-01 21:48:31.342933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '906e6e76a815'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jti', sa.String(), nullable=False),
    sa.Column('exp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blocked_tokens_id'), 'blocked_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_blocked_tokens_jti'), 'blocked_tokens', ['jti'], unique=True)
    op.create_table('federal_districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Человекочитаемое название региона РФ'),
    sa.Column('code_tv', sa.String(length=10), nullable=False, comment='Код региона на сайте "Работа России"'),
    sa.Column('code_hh', sa.String(length=10), nullable=False, comment='Код региона на сайте hh.ru'),
    sa.Column('federal_district_code', sa.String(length=10), nullable=False, comment='Код федерального округа, к которому относится регион'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_tv'),
    sa.UniqueConstraint('name'),
    comment='Справочник регионов РФ'
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('vacancies',
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный идентификатор записи'),
    sa.Column('vacancy_id', sa.String(length=300), nullable=False, comment='Идентификатор вакансии на сайте-источнике (например, hh.ru, trudvsem.ru)'),
    sa.Column('location', sa.String(length=300), nullable=False, comment='Город или населенный пункт, где расположена вакансия'),
    sa.Column('name', sa.String(length=300), nullable=False, comment='Название или должность вакансии'),
    sa.Column('description', sa.Text(), nullable=False, comment='Полное описание требований и обязанностей вакансии'),
    sa.Column('salary', sa.String(length=300), nullable=False, comment='Информация о заработной плате (например, "от 50000", "до 100000", "по договоренности")'),
    sa.Column('vacancy_url', sa.Text(), nullable=False, comment='Полный URL-адрес вакансии на сайте-источнике'),
    sa.Column('vacancy_source', sa.String(length=100), nullable=False, comment='Название сайта-источника вакансии (например, "hh.ru", "trudvsem.ru")'),
    sa.Column('employer_name', sa.String(length=300), nullable=False, comment='Наименование компании-работодателя'),
    sa.Column('employer_location', sa.Text(), nullable=False, comment='Адрес расположения работодателя'),
    sa.Column('employer_phone', sa.String(length=100), nullable=False, comment='Контактный номер телефона работодателя'),
    sa.Column('employer_code', sa.String(length=100), nullable=False, comment='Идентификатор работодателя на сайте-источнике'),
    sa.Column('experience_required', sa.Text(), nullable=False, comment='Требуемый опыт работы для соискателя'),
    sa.Column('category', sa.String(length=100), nullable=False, comment='Категория, к которой относится вакансия (например, "IT", "Продажи")'),
    sa.Column('employment_type', sa.String(length=200), nullable=False, comment='Тип занятости (например, "Полная", "Частичная", "Проектная")'),
    sa.Column('schedule', sa.Text(), nullable=False, comment='График работы (например, "Полный день", "Гибкий график", "Удаленная работа")'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vacancy_id', name='uq_vacancies_vacancy_id')
    )
    op.create_table('email_verification_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite_vacancies',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный идентификатор записи'),
    sa.Column('vacancy_id', sa.String(length=300), nullable=False, comment='Идентификатор вакансии на сайте-источнике (например, hh.ru, trudvsem.ru)'),
    sa.Column('location', sa.String(length=300), nullable=False, comment='Город или населенный пункт, где расположена вакансия'),
    sa.Column('name', sa.String(length=300), nullable=False, comment='Название или должность вакансии'),
    sa.Column('description', sa.Text(), nullable=False, comment='Полное описание требований и обязанностей вакансии'),
    sa.Column('salary', sa.String(length=300), nullable=False, comment='Информация о заработной плате (например, "от 50000", "до 100000", "по договоренности")'),
    sa.Column('vacancy_url', sa.Text(), nullable=False, comment='Полный URL-адрес вакансии на сайте-источнике'),
    sa.Column('vacancy_source', sa.String(length=100), nullable=False, comment='Название сайта-источника вакансии (например, "hh.ru", "trudvsem.ru")'),
    sa.Column('employer_name', sa.String(length=300), nullable=False, comment='Наименование компании-работодателя'),
    sa.Column('employer_location', sa.Text(), nullable=False, comment='Адрес расположения работодателя'),
    sa.Column('employer_phone', sa.String(length=100), nullable=False, comment='Контактный номер телефона работодателя'),
    sa.Column('employer_code', sa.String(length=100), nullable=False, comment='Идентификатор работодателя на сайте-источнике'),
    sa.Column('experience_required', sa.Text(), nullable=False, comment='Требуемый опыт работы для соискателя'),
    sa.Column('category', sa.String(length=100), nullable=False, comment='Категория, к которой относится вакансия (например, "IT", "Продажи")'),
    sa.Column('employment_type', sa.String(length=200), nullable=False, comment='Тип занятости (например, "Полная", "Частичная", "Проектная")'),
    sa.Column('schedule', sa.Text(), nullable=False, comment='График работы (например, "Полный день", "Гибкий график", "Удаленная работа")'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'vacancy_id', name='unique_user_id_vacancy_id')
    )
    op.create_table('password_reset_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('password_reset_codes')
    op.drop_table('favorite_vacancies')
    op.drop_table('email_verification_codes')
    op.drop_table('vacancies')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('regions')
    op.drop_table('federal_districts')
    op.drop_index(op.f('ix_blocked_tokens_jti'), table_name='blocked_tokens')
    op.drop_index(op.f('ix_blocked_tokens_id'), table_name='blocked_tokens')
    op.drop_table('blocked_tokens')
    # ### end Alembic commands ###
