"""Delete Changing a Unique Constraint

Revision ID: ff78f8a57578
Revises: f3821a84c393
Create Date: 2026-02-22 17:17:30.213363

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ff78f8a57578'
down_revision: Union[str, None] = 'f3821a84c393'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_vacancies_vacancy_id', 'vacancies', type_='unique')
    op.create_unique_constraint('unique_vacancies_vacancy_id__location', 'vacancies', ['vacancy_id', 'location'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_vacancies_vacancy_id__location', 'vacancies', type_='unique')
    op.create_unique_constraint('uq_vacancies_vacancy_id', 'vacancies', ['vacancy_id'])
    # ### end Alembic commands ###
