"""Model update for Favorites

Revision ID: d467316b7c60
Revises: 906e6e76a815
Create Date: 2026-02-09 20:02:29.057050

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd467316b7c60'
down_revision: Union[str, None] = '906e6e76a815'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('favorite_vacancies_user_id_fkey', 'favorite_vacancies', type_='foreignkey')
    op.alter_column('favorite_vacancies', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=300),
               comment='ID пользователя (Telegram ID, email, любой другой внещний ID) для связи вакансии.',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('favorite_vacancies_user_id_fkey', 'favorite_vacancies', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('favorite_vacancies', 'user_id',
               existing_type=sa.String(length=300),
               type_=sa.INTEGER(),
               comment=None,
               existing_comment='ID пользователя (Telegram ID, email, любой другой внещний ID) для связи вакансии.',
               existing_nullable=False)
    # ### end Alembic commands ###
