"""Add ApiKey model

Revision ID: f3821a84c393
Revises: 0d58fb317501
Create Date: 2026-02-09 21:08:05.949396

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f3821a84c393'
down_revision: Union[str, None] = '0d58fb317501'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный идентификатор API-ключа.'),
    sa.Column('hashed_key', sa.String(length=255), nullable=False, comment='Односторонний хэш API-ключа (например, SHA-256), хранимый в базе данных.'),
    sa.Column('api_key_prefix', sa.String(length=16), nullable=False, comment='Часть API-ключа (например, первые 8-16 символов), используемая для отладки и идентификации в логах.'),
    sa.Column('issued_for', sa.String(length=100), nullable=False, comment='Назначение API-ключа (например, "website", "telegram_bot", "mobile_app").'),
    sa.Column('owner_email', sa.String(length=255), nullable=False, comment='Адрес электронной почты лица или организации, ответственной за API-ключ.'),
    sa.Column('comment', sa.Text(), nullable=True, comment='Произвольный комментарий для внутреннего использования (например, цель использования, дата выдачи).'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Метка времени создания записи API-ключа.'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='Метка времени, после которой API-ключ считается недействительным (необязательно).'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Булево значение, указывающее, является ли API-ключ активным (True) или деактивированным (False).'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key_prefix')
    )
    op.create_index(op.f('ix_api_keys_hashed_key'), 'api_keys', ['hashed_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_keys_hashed_key'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
