"""Add AssistantSession model

Revision ID: 283658b8f59a
Revises: ff78f8a57578
Create Date: 2026-03-14 14:37:23.376424

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '283658b8f59a'
down_revision: Union[str, None] = 'ff78f8a57578'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistant_sessions',
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный идентификатор записи сессии AI-ассистента.'),
    sa.Column('session_type', sa.String(length=50), nullable=False, comment='Тип вызова ассистента. Возможные значения: cover_letter_by_vacancy, resume_tips_by_vacancy, letter_questionnaire, resume_questionnaire, cover_letter_by_questionnaire, resume_tips_by_questionnaire.'),
    sa.Column('vacancy_id', sa.String(length=100), nullable=False, comment='ID вакансии из источника (hh.ru или trudvsem.ru). Используется для фильтрации.'),
    sa.Column('vacancy_name', sa.Text(), nullable=False, comment='Название должности/вакансии, переданное в промпт LLM.'),
    sa.Column('employer_name', sa.Text(), nullable=True, comment='Наименование организации-работодателя, переданное в промпт LLM.'),
    sa.Column('employer_location', sa.Text(), nullable=True, comment='Адрес рабочего места, переданный в промпт LLM.'),
    sa.Column('employment', sa.Text(), nullable=True, comment='Тип занятости (полный день, удалённо и т.д.), переданный в промпт LLM.'),
    sa.Column('salary', sa.Text(), nullable=True, comment='Зарплатные данные вакансии, переданные в промпт LLM.'),
    sa.Column('description', sa.Text(), nullable=True, comment='Полный текст описания вакансии (обязанности, требования), переданный в промпт LLM.'),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON-массив ответов соискателя: [{id, text, answer}]. NULL для остальных типов сессий.'),
    sa.Column('result', sa.Text(), nullable=False, comment='Сырой результат, возвращённый LLM. Для questionnaire-типов — JSON, для остальных — HTML.'),
    sa.Column('llm_model', sa.String(length=100), nullable=False, comment='Название/ID модели LLM (например, "deepseek-r1"), которая сгенерировала результат.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Метка времени создания записи сессии AI-ассистента.'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assistant_sessions_session_type'), 'assistant_sessions', ['session_type'], unique=False)
    op.create_index(op.f('ix_assistant_sessions_vacancy_id'), 'assistant_sessions', ['vacancy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assistant_sessions_vacancy_id'), table_name='assistant_sessions')
    op.drop_index(op.f('ix_assistant_sessions_session_type'), table_name='assistant_sessions')
    op.drop_table('assistant_sessions')
    # ### end Alembic commands ###
